### ISSUE TITLE
game is all shutdown in 2.0.0 

### ISSUE THREAD

**Issue by VincentRi4144** [asesidaa/EXVS2-POC#82] opened 2023-10-15 13:35 UTC
the game frozen and shutdown itself after I selected the interface name in Radmin VPN and clicked the start clicent button.
![c](https://github.com/asesidaa/EXVS2-POC/assets/43128102/a2ee1718-814b-466b-beba-a9ef92b37e1a)

before, the game is fully launchable if I use the 1.1.0 version

**Comment by oppenheimerbeach** [comment] 2023-10-17 04:25
Please check if your path has any special characters (Chinese, Korean, Japanese), and if that does not work please try place your game on a drive that does not have drive letter of F: and G:

**Comment by VincentRi4144** [comment] 2023-10-17 13:30
![image](https://github.com/asesidaa/EXVS2-POC/assets/43128102/7d87958c-baab-44d6-acd5-078b8c4bd1b5)
still not working

**Comment by oppenheimerbeach** [comment] 2023-10-17 13:35
Run iauthdll.bat inside AMCUS folder with administrative privilege, and try again.

**Comment by VincentRi4144** [comment] 2023-10-18 12:29
![0](https://github.com/asesidaa/EXVS2-POC/assets/43128102/38634c98-e6f9-46b6-9d27-1827e4e45e0c)
![0 5](https://github.com/asesidaa/EXVS2-POC/assets/43128102/968ab86e-640b-4e96-a116-cc558e85a0c9)
![2](https://github.com/asesidaa/EXVS2-POC/assets/43128102/8ea8a59a-8697-4464-8ac1-a4b860d1a643)
still the game crashed itself

**Comment by oppenheimerbeach** [comment] 2023-10-19 13:35
Would recommend you do a clean installation of 2.0 again.

**Comment by VincentRi4144** [comment] 2023-10-23 07:42
It works now after I reinstalled windows10 system and followed the same step I did before.

**Comment by oppenheimerbeach** [comment] 2023-10-27 01:58
Thanks for reporting.

From my sources, seems like a full system reset sometimes fixes the issue. 

Every time this error showed up is probably because the exe was incompatible with the user's PC setup, which can be caused by a myriad of issues like driver, hardware etc. 

Hardly surprising since the error message is a catch all error message that shows you when your game crashes (the UI just launches an monitoring exe that helps you kill the task if the game is closed, thus the error message).

Not sure if there's anything we can do for now, probably a better error message instead of a generic one.
For anyone stumbling on this issue please do a clean install, and if worst comes to worst, do a full system reset (Although I personally wouldn't go that far for a game).

Closing this issue for now, unless more information comes up in the future.

**Closed as completed by oppenheimerbeach** 2023-10-27 01:58 UTC
